name: Refined Diff and Folder Check

on:
  push:
    branches:
      - main

jobs:
  refined-diff-folder-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Categorize Changes
      run: |
        git fetch origin main
        ADDED_FILES=$(git diff --name-status --diff-filter=A HEAD~1 HEAD | awk '{print $2}')
        REMOVED_FILES=$(git diff --name-status --diff-filter=D HEAD~1 HEAD | awk '{print $2}')
        MODIFIED_FILES=$(git diff --name-status --diff-filter=M HEAD~1 HEAD | awk '{print $2}')
        
        ADDED_FOLDERS=""
        REMOVED_FOLDERS=""
        MODIFIED_FOLDERS=""

        for FILE in $ADDED_FILES; do
          DIR=$(dirname "$FILE")
          while [ "$DIR" != "." ]; do
            ADDED_FOLDERS+=" $DIR"
            DIR=$(dirname "$DIR")
          done
        done

        for FILE in $REMOVED_FILES; do
          DIR=$(dirname "$FILE")
          while [ "$DIR" != "." ]; do
            REMOVED_FOLDERS+=" $DIR"
            DIR=$(dirname "$DIR")
          done
        done

        for FILE in $MODIFIED_FILES; do
          DIR=$(dirname "$FILE")
          while [ "$DIR" != "." ]; do
            MODIFIED_FOLDERS+=" $DIR"
            DIR=$(dirname "$DIR")
          done
        done

        echo "Added Files: $ADDED_FILES"
        echo "Removed Files: $REMOVED_FILES"
        echo "Modified Files: $MODIFIED_FILES"
        echo "Added Folders: $ADDED_FOLDERS"
        echo "Removed Folders: $REMOVED_FOLDERS"
        echo "Modified Folders: $MODIFIED_FOLDERS"
