name: Update Mirror File Tree

on:
  push:
    branches:
      - main

jobs:
  update-mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get Changed Files
      id: getfile
      run: |
        echo "modified=$(git diff --name-only --diff-filter=M HEAD~1)" >> $GITHUB_ENV
        echo "added=$(git diff --name-only --diff-filter=A HEAD~1)" >> $GITHUB_ENV
        echo "deleted=$(git diff --name-only --diff-filter=D HEAD~1)" >> $GITHUB_ENV
        echo "renamed=$(git diff --name-status --diff-filter=R HEAD~1 | awk '{print $2 " => " $3}')" >> $GITHUB_ENV

    - name: Handle Changes
      run: |
        echo "Modified files: $modified"
        echo "Added files: $added"
        echo "Deleted files: $deleted"
        echo "Renamed files: $renamed"
        # Add your procedures for handling the changes here