name: Update Mirror File Tree

on:
  push:
    branches:
      - main

jobs:
  update-mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get Changed Files
      id: getfile
      shell: bash
      run: |
        modified=($(git diff --name-only --diff-filter=M HEAD~1))
        added=($(git diff --name-only --diff-filter=A HEAD~1))
        deleted=($(git diff --name-only --diff-filter=D HEAD~1))
        renamed=($(git diff --name-status --diff-filter=R HEAD~1 | awk '{print $2 " => " $3}'))
        
        echo "modified=${modified[*]}" >> $GITHUB_ENV
        echo "added=${added[*]}" >> $GITHUB_ENV
        echo "deleted=${deleted[*]}" >> $GITHUB_ENV
        echo "renamed=${renamed[*]}" >> $GITHUB_ENV

    - name: Handle Changes
      run: |
        echo "Modified files: $modified"
        echo "Added files: $added"
        echo "Deleted files: $deleted"
        echo "Renamed files: $renamed"
        # Add your procedures for handling the changes here

    - name: Run OpenAI Script
      run: python DoPE.py