name: Debugged Diff and Folder Check

on:
  push:
    branches:
      - main

jobs:
  debugged-diff-folder-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Categorize Changes
      run: |
        git fetch --depth=50 origin main
        COMMIT_RANGE="${{ github.event.before }}..${{ github.sha }}"
        ADDED_FILES=$(git diff --name-status --diff-filter=A $COMMIT_RANGE | awk '{print $2}')
        REMOVED_FILES=$(git diff --name-status --diff-filter=D $COMMIT_RANGE | awk '{print $2}')
        MODIFIED_FILES=$(git diff --name-status --diff-filter=M $COMMIT_RANGE | awk '{print $2}')
        RENAMED=$(git diff --name-status --diff-filter=R $COMMIT_RANGE | awk '{print $2 " " $3}')

        ADDED_FOLDERS=""
        REMOVED_FOLDERS=""
        MODIFIED_FOLDERS=""

        for FILE in $ADDED_FILES; do
          DIR=$(dirname "$FILE")
          while [ "$DIR" != "." ]; do
            ADDED_FOLDERS+=" $DIR"
            DIR=$(dirname "$DIR")
          done
        done

        for FILE in $REMOVED_FILES; do
          DIR=$(dirname "$FILE")
          while [ "$DIR" != "." ]; do
            REMOVED_FOLDERS+=" $DIR"
            DIR=$(dirname "$DIR")
          done
        done

        for FILE in $MODIFIED_FILES; do
          DIR=$(dirname "$FILE")
          while [ "$DIR" != "." ]; do
            MODIFIED_FOLDERS+=" $DIR"
            DIR=$(dirname "$DIR")
          done
        done

        for LINE in $RENAMED; do
          FROM=$(echo $LINE | awk '{print $1}')
          TO=$(echo $LINE | awk '{print $2}')
          REMOVED_FILES+=" $FROM"
          ADDED_FILES+=" $TO"

          FROM_DIR=$(dirname "$FROM")
          TO_DIR=$(dirname "$TO")

          while [ "$FROM_DIR" != "." ]; do
            REMOVED_FOLDERS+=" $FROM_DIR"
            FROM_DIR=$(dirname "$FROM_DIR")
          done

          while [ "$TO_DIR" != "." ]; do
            ADDED_FOLDERS+=" $TO_DIR"
            TO_DIR=$(dirname "$TO_DIR")
          done
        done

        echo "Added Files: $ADDED_FILES"
        echo "Removed Files: $REMOVED_FILES"
        echo "Modified Files: $MODIFIED_FILES"
        echo "Added Folders: $ADDED_FOLDERS"
        echo "Removed Folders: $REMOVED_FOLDERS"
        echo "Modified Folders: $MODIFIED_FOLDERS"
