name: Update Mirror File Tree

on:
  push:
    branches:
      - main

jobs:
  update-mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get Changed Files
      id: getfile
      run: |
        echo "::set-output name=modified::$(git diff --name-only --diff-filter=M HEAD~1)"
        echo "::set-output name=added::$(git diff --name-only --diff-filter=A HEAD~1)"
        echo "::set-output name=deleted::$(git diff --name-only --diff-filter=D HEAD~1)"

    - name: Handle Changes
      run: |
        echo "Modified files: ${{ steps.getfile.outputs.modified }}"
        echo "Added files: ${{ steps.getfile.outputs.added }}"
        echo "Deleted files: ${{ steps.getfile.outputs.deleted }}"
        # Add your procedures for handling the changes here